services:
  - type: web
    name: grammarcheck
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
      